#!/bin/bash
progname=$(dirname $0)
case `uname -s` in
    Linux)  OS=Linux;;
    Darwin) OS=OSX;;
    *)	    OS=Other;;
esac
case `uname -m` in
    x86_64) ARCH=x64 ;;
    i386)   ARCH=x86 ;;
    arm*)   ARCH=arm ;;
    *)	    ARCH=Unknown ;;
esac
case $OS in
    OSX) OSARCH=$OS;;
    *)   OSARCH=$OS/$ARCH;;
esac
case $OS in
    Linux) export LD_LIBRARY_PATH=`readlink -f $progname/bin/$OSARCH/`:$LD_LIBRARY_PATH;;
esac
"$progname/bin/$OSARCH/luajit" "$@"
